CREATE TABLE "ADMIN"."MARKETDATA_META" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"SYMBOL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"COUNTRY_CODE" VARCHAR2(10 BYTE) DEFAULT 'KR' NOT NULL ENABLE, 
	"MARKET" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"NAME" VARCHAR2(100 BYTE) NOT NULL ENABLE, 
	"DATA_TYPE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"INSTRUMENT_TYPE" VARCHAR2(20 BYTE) DEFAULT 'SINGLE' NOT NULL ENABLE, 
	"SOURCE" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA" ;
ALTER TABLE "ADMIN"."MARKETDATA_META" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 20 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "DATA"  ENABLE;

   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."SYMBOL" IS '상품코드';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."COUNTRY_CODE" IS '국가 코드';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."MARKET" IS '시장구분(EQ: Equity, IR: Interest Rate, FX: Forex, CM: Commodity)';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."NAME" IS '상품명';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."DATA_TYPE" IS '상품종류(Spot, Futures, ETF, ...)';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."INSTRUMENT_TYPE" IS '상품 유형(SINGLE:개별종목, CONTINUOUS:연결선물, INDEX:지수 등)';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."SOURCE" IS '데이터 출처(infomax, bloomberg, ...)';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "ADMIN"."MARKETDATA_META"."UPDATED_AT" IS '마지막 수정일시';