CREATE TABLE "ADMIN"."MARKETDATA_PRICE_RT" 
   (	"ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"TIMESTAMP" TIMESTAMP (6) NOT NULL ENABLE, 
	"SYMBOL" VARCHAR2(20 BYTE) NOT NULL ENABLE, 
	"PRICE" NUMBER(20,4), 
	"VOLUME" NUMBER(20,0), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 10 MAXTRANS 255 
 COLUMN STORE COMPRESS FOR QUERY HIGH ROW LEVEL LOCKING LOGGING
  TABLESPACE "DATA" ;